version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ghasedak
      POSTGRES_USER: ghasedak
      POSTGRES_PASSWORD: ghasedak
    ports:
      - 5432:5432
