version: '3.1'
services:
  pulsar:
    image: apachepulsar/pulsar
    container_name: pulsar
    ports:
      - 6650:6650 
    environment:
      - PULSAR_MEM="-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
